export const bancoTypes = {
    BANCO_GET: 'BANCO_GET',
    BANCO_GET_SUCCESS: 'BANCO_GET_SUCCESS',
    BANCO_GET_FAILURE: 'BANCO_GET_FAILURE',

    BANCO_UPDATE: 'BANCO_UPDATE',
    BANCO_UPDATE_SUCCESS: 'BANCO_UPDATE_SUCCESS',
    BANCO_UPDATE_FAILURE: 'BANCO_UPDATE_FAILURE',

    BANCO_CREATE: 'BANCO_CREATE',
    BANCO_CREATE_SUCCESS: 'BANCO_CREATE_SUCCESS',
    BANCO_CREATE_FAILURE: 'BANCO_CREATE_FAILURE',

    BANCO_GET_ALL: 'BANCO_GET_ALL',
    BANCO_GET_AL_SUCCESSL: 'BANCO_GET_ALL_SUCCESS',
    BANCO_GET_ALL_FAILURE: 'BANCO_GET_ALL_FAILURE', 

    BANCO_FILTER: 'BANCO_FILTER'
};