export const bancoClientTypes = {
    BANCO_CLIENT_GET: 'BANCO_CLIENT_GET',
    BANCO_CLIENT_GET_SUCCESS: 'BANCO_CLIENT_GET_SUCCESS',
    BANCO_CLIENT_GET_FAILURE: 'BANCO_CLIENT_GET_FAILURE',

    BANCO_CLIENT_UPDATE: 'BANCO_CLIENT_UPDATE',
    BANCO_CLIENT_UPDATE_SUCCESS: 'BANCO_CLIENT_UPDATE_SUCCESS',
    BANCO_CLIENT_UPDATE_FAILURE: 'BANCO_CLIENT_UPDATE_FAILURE',

    BANCO_CLIENT_CREATE: 'BANCO_CLIENT_CREATE',
    BANCO_CLIENT_CREATE_SUCCESS: 'BANCO_CLIENT_CREATE_SUCCESS',
    BANCO_CLIENT_CREATE_FAILURE: 'BANCO_CLIENT_CREATE_FAILURE',

    BANCO_CLIENT_GET_ALL: 'BANCO_CLIENT_GET_ALL',
    BANCO_CLIENT_GET_AL_SUCCESSL: 'BANCO_CLIENT_GET_ALL_SUCCESS',
    BANCO_CLIENT_GET_ALL_FAILURE: 'BANCO_CLIENT_GET_ALL_FAILURE', 

    BANCO_CLIENT_DELETE: 'BANCO_CLIENT_DELETE',
    BANCO_CLIENT_DELETE_SUCCESS: 'BANCO_CLIENT_DELETE_SUCCESS',
    BANCO_CLIENT_DELETE_FAILURE: 'BANCO_CLIENT_DELETE_FAILURE',

    BANCO_CLIENT_FILTER: 'BANCO_CLIENT_FILTER'
};