export const configuracaoTypes = {
    CONFIGURACAO_SAVE_REQUEST: 'CONFIGURACAO_SAVE_REQUEST',
    CONFIGURACAO_SAVE_SUCCESS: 'CONFIGURACAO_SAVE_SUCCESS',
    CONFIGURACAO_SAVE_FAILURE: 'CONFIGURACAO_SAVE_FAILURE',

    CONFIGURACAO_GET_REQUEST: 'CONFIGURACAO_GET_REQUEST',
    CONFIGURACAO_GET_SUCCESS: 'CONFIGURACAO_GET_SUCCESS',
    CONFIGURACAO_GET_FAILURE: 'CONFIGURACAO_GET_FAILURE',
};
