export const historicoOperacoesTypes = {
    HISTORICO_OPERACOES_GET: 'HISTORICO_OPERACOES_GET',
    HISTORICO_OPERACOES_GET_SUCCESS: 'HISTORICO_OPERACOES_GET_SUCCESS',
    HISTORICO_OPERACOES_GET_FAILURE: 'HISTORICO_OPERACOES_GET_FAILURE',

    HISTORICO_OPERACOES_GET_ALL: 'HISTORICO_OPERACOES_GET_ALL',
    HISTORICO_OPERACOES_GET_AL_SUCCESSL: 'HISTORICO_OPERACOES_GET_ALL_SUCCESS',
    HISTORICO_OPERACOES_GET_ALL_FAILURE: 'HISTORICO_OPERACOES_GET_ALL_FAILURE', 

    HISTORICO_OPERACOES_FILTER: 'HISTORICO_OPERACOES_FILTER'
};