const Client = {
    id: '',
    type: '',
    name: '',
    nickname: '',
    gender: '',
    cpf: '',
    rg: '',
    birthDate: null,
    nome_pai: '',
    nome_mae: '',
    estado_civil: '',
    conjugue: '',
    credit: 0,
    disponivel: 0,
    limit: 0,
    acrescimo: 0,
    local_trabalho: '',
    renda_mensal: 0,
    cargo: '',
    user_id: null,
    bancoClient: null,
    enderecoClient: null,
    telefoneClient: null,
    emailClient: null,
    referenciaClient: null,
  }

  export default Client;
