const Client = {
    id: '',
    type: '',
    name: '',
    nickname: '',
    gender: '',
    cpf: '',
    rg: '',
    birthDate: null,
    nome_pai: '',
    nome_mae: '',
    estado_civil: '',
    conjugue: '',
    credit: '',
    limit: '',
    acrescimo: '',
    local_trabalho: '',
    renda_mensal: '',
    cargo: '',
    user_id: '',
    bancoClient: null,
    enderecoClient: null,
    telefoneClient: null,
    emailClient: null,
    referenciaClient: null,
  }

  export default Client;