export const enderecoClientTypes = {
    EMAIL_CLIENT_GET: 'EMAIL_CLIENT_GET',
    EMAIL_CLIENT_GET_SUCCESS: 'EMAIL_CLIENT_GET_SUCCESS',
    EMAIL_CLIENT_GET_FAILURE: 'EMAIL_CLIENT_GET_FAILURE',

    EMAIL_CLIENT_UPDATE: 'EMAIL_CLIENT_UPDATE',
    EMAIL_CLIENT_UPDATE_SUCCESS: 'EMAIL_CLIENT_UPDATE_SUCCESS',
    EMAIL_CLIENT_UPDATE_FAILURE: 'EMAIL_CLIENT_UPDATE_FAILURE',

    EMAIL_CLIENT_CREATE: 'EMAIL_CLIENT_CREATE',
    EMAIL_CLIENT_CREATE_SUCCESS: 'EMAIL_CLIENT_CREATE_SUCCESS',
    EMAIL_CLIENT_CREATE_FAILURE: 'EMAIL_CLIENT_CREATE_FAILURE',

    EMAIL_CLIENT_GET_ALL: 'EMAIL_CLIENT_GET_ALL',
    EMAIL_CLIENT_GET_AL_SUCCESSL: 'EMAIL_CLIENT_GET_ALL_SUCCESS',
    EMAIL_CLIENT_GET_ALL_FAILURE: 'EMAIL_CLIENT_GET_ALL_FAILURE', 

    EMAIL_CLIENT_DELETE: 'EMAIL_CLIENT_DELETE',
    EMAIL_CLIENT_DELETE_SUCCESS: 'EMAIL_CLIENT_DELETE_SUCCESS',
    EMAIL_CLIENT_DELETE_FAILURE: 'EMAIL_CLIENT_DELETE_FAILURE',

    EMAIL_CLIENT_FILTER: 'EMAIL_CLIENT_FILTER'
};