export const clientTypes = {
    CLIENT_GET: 'CLIENT_GET',
    CLIENT_GET_SUCCESS: 'CLIENT_GET_SUCCESS',
    CLIENT_GET_FAILURE: 'CLIENT_GET_FAILURE',

    CLIENT_UPDATE: 'CLIENT_UPDATE',
    CLIENT_UPDATE_SUCCESS: 'CLIENT_UPDATE_SUCCESS',
    CLIENT_UPDATE_FAILURE: 'CLIENT_UPDATE_FAILURE',

    CLIENT_CREATE: 'CLIENT_CREATE',
    CLIENT_CREATE_SUCCESS: 'CLIENT_CREATE_SUCCESS',
    CLIENT_CREATE_FAILURE: 'CLIENT_CREATE_FAILURE',

    CLIENT_GET_ALL: 'CLIENT_GET_ALL',
    CLIENT_GET_AL_SUCCESSL: 'CLIENT_GET_ALL_SUCCESS',
    CLIENT_GET_ALL_FAILURE: 'CLIENT_GET_ALL_FAILURE', 
};