export const chequeTypes = {
    CHEQUE_GET: 'CHEQUE_GET',
    CHEQUE_GET_SUCCESS: 'CHEQUE_GET_SUCCESS',
    CHEQUE_GET_FAILURE: 'CHEQUE_GET_FAILURE',

    CHEQUE_UPDATE: 'CHEQUE_UPDATE',
    CHEQUE_UPDATE_SUCCESS: 'CHEQUE_UPDATE_SUCCESS',
    CHEQUE_UPDATE_FAILURE: 'CHEQUE_UPDATE_FAILURE',

    CHEQUE_CREATE: 'CHEQUE_CREATE',
    CHEQUE_CREATE_SUCCESS: 'CHEQUE_CREATE_SUCCESS',
    CHEQUE_CREATE_FAILURE: 'CHEQUE_CREATE_FAILURE',

    CHEQUE_GET_ALL: 'CHEQUE_GET_ALL',
    CHEQUE_GET_AL_SUCCESSL: 'CHEQUE_GET_ALL_SUCCESS',
    CHEQUE_GET_ALL_FAILURE: 'CHEQUE_GET_ALL_FAILURE', 

    CHEQUE_FILTER: 'CHEQUE_FILTER'
};