export const referenciaClientTypes = {
    REFERENCIA_CLIENT_GET: 'REFERENCIA_CLIENT_GET',
    REFERENCIA_CLIENT_GET_SUCCESS: 'REFERENCIA_CLIENT_GET_SUCCESS',
    REFERENCIA_CLIENT_GET_FAILURE: 'REFERENCIA_CLIENT_GET_FAILURE',

    REFERENCIA_CLIENT_UPDATE: 'REFERENCIA_CLIENT_UPDATE',
    REFERENCIA_CLIENT_UPDATE_SUCCESS: 'REFERENCIA_CLIENT_UPDATE_SUCCESS',
    REFERENCIA_CLIENT_UPDATE_FAILURE: 'REFERENCIA_CLIENT_UPDATE_FAILURE',

    REFERENCIA_CLIENT_CREATE: 'REFERENCIA_CLIENT_CREATE',
    REFERENCIA_CLIENT_CREATE_SUCCESS: 'REFERENCIA_CLIENT_CREATE_SUCCESS',
    REFERENCIA_CLIENT_CREATE_FAILURE: 'REFERENCIA_CLIENT_CREATE_FAILURE',

    REFERENCIA_CLIENT_GET_ALL: 'REFERENCIA_CLIENT_GET_ALL',
    REFERENCIA_CLIENT_GET_AL_SUCCESSL: 'REFERENCIA_CLIENT_GET_ALL_SUCCESS',
    REFERENCIA_CLIENT_GET_ALL_FAILURE: 'REFERENCIA_CLIENT_GET_ALL_FAILURE', 

    REFERENCIA_CLIENT_DELETE: 'REFERENCIA_CLIENT_DELETE',
    REFERENCIA_CLIENT_DELETE_SUCCESS: 'REFERENCIA_CLIENT_DELETE_SUCCESS',
    REFERENCIA_CLIENT_DELETE_FAILURE: 'REFERENCIA_CLIENT_DELETE_FAILURE',

    REFERENCIA_CLIENT_FILTER: 'REFERENCIA_CLIENT_FILTER'
};