export const userTypes = {
    USERS_CREATE_REQUEST: 'USERS_CREATE_REQUEST',
    USERS_CREATE_SUCCESS: 'USERS_CREATE_SUCCESS',
    USERS_CREATE_FAILURE: 'USERS_CREATE_FAILURE',

    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    LOGOUT: 'USERS_LOGOUT',

    USERS_GETALL_REQUEST: 'USERS_GETALL_REQUEST',
    USERS_GETALL_SUCCESS: 'USERS_GETALL_SUCCESS',
    USERS_GETALL_FAILURE: 'USERS_GETALL_FAILURE',

    USERS_GETBYID_REQUEST: 'USERS_GETBYID_REQUEST',
    USERS_GETBYID_SUCCESS: 'USERS_GETBYID_SUCCESS',
    USERS_GETBYID_FAILURE: 'USERS_GETBYID_FAILURE',

    USERS_UPDATE_REQUEST: 'USERS_UPDATE_REQUEST',
    USERS_UPDATE_SUCCESS: 'USERS_UPDATE_SUCCESS',
    USERS_UPDATE_FAILURE: 'USERS_UPDATE_FAILURE',

    USERS_FILTER_REQUEST: 'USERS_FILTER_REQUEST',
    USERS_FILTER_SUCCESS: 'USERS_FILTER_SUCCESS',
    USERS_FILTER_FAILURE: 'USERS_FILTER_FAILURE',

    USERS_DELETE_REQUEST: 'USERS_DELETE_REQUEST',
    USERS_DELETE_SUCCESS: 'USERS_DELETE_SUCCESS',
    USERS_DELETE_FAILURE: 'USERS_DELETE_FAILURE'
};
