export const operacaoTypes = {
    OPERACOES_GET: 'OPERACOES_GET',
    OPERACOES_GET_SUCCESS: 'OPERACOES_GET_SUCCESS',
    OPERACOES_GET_FAILURE: 'OPERACOES_GET_FAILURE',

    OPERACOES_UPDATE: 'OPERACOES_UPDATE',
    OPERACOES_UPDATE_SUCCESS: 'OPERACOES_UPDATE_SUCCESS',
    OPERACOES_UPDATE_FAILURE: 'OPERACOES_UPDATE_FAILURE',

    OPERACOES_CREATE: 'OPERACOES_CREATE',
    OPERACOES_CREATE_SUCCESS: 'OPERACOES_CREATE_SUCCESS',
    OPERACOES_CREATE_FAILURE: 'OPERACOES_CREATE_FAILURE',

    OPERACOES_GET_ALL: 'OPERACOES_GET_ALL',
    OPERACOES_GET_AL_SUCCESSL: 'OPERACOES_GET_ALL_SUCCESS',
    OPERACOES_GET_ALL_FAILURE: 'OPERACOES_GET_ALL_FAILURE', 

    OPERACOES_DELETE: 'OPERACOES_DELETE',
    OPERACOES_DELETE_SUCCESS: 'OPERACOES_DELETE_SUCCESS',
    OPERACOES_DELETE_FAILURE: 'OPERACOES_DELETE_FAILURE',

    OPERACOES_FILTER: 'OPERACOES_FILTER'
};