export const chequeOperacaoTypes = {
    CHEQUE_OPERACAO_GET: 'CHEQUE_OPERACAO_GET',
    CHEQUE_OPERACAO_GET_SUCCESS: 'CHEQUE_OPERACAO_GET_SUCCESS',
    CHEQUE_OPERACAO_GET_FAILURE: 'CHEQUE_OPERACAO_GET_FAILURE',

    CHEQUE_OPERACAO_UPDATE: 'CHEQUE_OPERACAO_UPDATE',
    CHEQUE_OPERACAO_UPDATE_SUCCESS: 'CHEQUE_OPERACAO_UPDATE_SUCCESS',
    CHEQUE_OPERACAO_UPDATE_FAILURE: 'CHEQUE_OPERACAO_UPDATE_FAILURE',

    CHEQUE_OPERACAO_CREATE: 'CHEQUE_OPERACAO_CREATE',
    CHEQUE_OPERACAO_CREATE_SUCCESS: 'CHEQUE_OPERACAO_CREATE_SUCCESS',
    CHEQUE_OPERACAO_CREATE_FAILURE: 'CHEQUE_OPERACAO_CREATE_FAILURE',

    CHEQUE_OPERACAO_GET_ALL: 'CHEQUE_OPERACAO_GET_ALL',
    CHEQUE_OPERACAO_GET_AL_SUCCESSL: 'CHEQUE_OPERACAO_GET_ALL_SUCCESS',
    CHEQUE_OPERACAO_GET_ALL_FAILURE: 'CHEQUE_OPERACAO_GET_ALL_FAILURE', 

    CHEQUE_OPERACAO_DELETE: 'CHEQUE_OPERACAO_DELETE',
    CHEQUE_OPERACAO_DELETE_SUCCESS: 'CHEQUE_OPERACAO_DELETE_SUCCESS',
    CHEQUE_OPERACAO_DELETE_FAILURE: 'CHEQUE_OPERACAO_DELETE_FAILURE',

    CHEQUE_OPERACAO_FILTER: 'CHEQUE_OPERACAO_FILTER'
};