export const telefoneClientTypes = {
    TELEFONE_CLIENT_GET: 'TELEFONE_CLIENT_GET',
    TELEFONE_CLIENT_GET_SUCCESS: 'TELEFONE_CLIENT_GET_SUCCESS',
    TELEFONE_CLIENT_GET_FAILURE: 'TELEFONE_CLIENT_GET_FAILURE',

    TELEFONE_CLIENT_UPDATE: 'TELEFONE_CLIENT_UPDATE',
    TELEFONE_CLIENT_UPDATE_SUCCESS: 'TELEFONE_CLIENT_UPDATE_SUCCESS',
    TELEFONE_CLIENT_UPDATE_FAILURE: 'TELEFONE_CLIENT_UPDATE_FAILURE',

    TELEFONE_CLIENT_CREATE: 'TELEFONE_CLIENT_CREATE',
    TELEFONE_CLIENT_CREATE_SUCCESS: 'TELEFONE_CLIENT_CREATE_SUCCESS',
    TELEFONE_CLIENT_CREATE_FAILURE: 'TELEFONE_CLIENT_CREATE_FAILURE',

    TELEFONE_CLIENT_GET_ALL: 'TELEFONE_CLIENT_GET_ALL',
    TELEFONE_CLIENT_GET_AL_SUCCESSL: 'TELEFONE_CLIENT_GET_ALL_SUCCESS',
    TELEFONE_CLIENT_GET_ALL_FAILURE: 'TELEFONE_CLIENT_GET_ALL_FAILURE', 

    TELEFONE_CLIENT_DELETE: 'TELEFONE_CLIENT_DELETE',
    TELEFONE_CLIENT_DELETE_SUCCESS: 'TELEFONE_CLIENT_DELETE_SUCCESS',
    TELEFONE_CLIENT_DELETE_FAILURE: 'TELEFONE_CLIENT_DELETE_FAILURE',

    TELEFONE_CLIENT_FILTER: 'TELEFONE_CLIENT_FILTER'
};